### ISSUE TITLE
Add - Rating Bar to Rating and Profile Page 

### ISSUE THREAD

**Issue by imaginaryBuddy** [bertrainn/SC2006_Depressed-Mahjong-Tables#6]
If anyone is free, do take a look at this: https://pub.dev/packages/flutter_rating_bar
Then if you can implement into the app, you can try. 
https://www.youtube.com/watch?v=VdkRy3yZiPo

**Comment by johnny-psh** [comment]
If anyone is free -> Look at implementation

Since nobody is free, we don't need to look at the implementation
